[package]
name = "elaina"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast = { path = "ast" }
ast_lowering = { path = "ast_lowering" }
index = { path = "index" }
ir = { path = "ir" }
lexer = {path = "lexer" }
parser = { path = "parser" }
clap = { version = "3.0.14", features = ["derive"] }
