[package]
name = "ty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
span = { path = "../span" }
typed-arena = "2.0.1"
