use ir::{constant::*, stmt::*, *};
use thir;

use std::collections::HashMap;

#[allow(dead_code)]
pub struct LoweringContext {
    body: Body,

    block_at: BlockId,

    local_name_table: HashMap<String, Place>,
}

impl LoweringContext {
    pub fn new() -> Self {
        LoweringContext {
            body: Body::new(),
            block_at: BlockId::dummy(),
            local_name_table: HashMap::new(),
        }
    }

    pub fn build(self) -> Body {
        self.body
    }

    pub fn lower_main_block(&mut self, block: &thir::Block) {
        self.block_at = self.body.blocks.push_and_get_key(Block::new());

        for stmt in &block.stmts {
            self.lower_stmt(stmt);
        }
    }

    fn lower_stmt(&mut self, stmt: &thir::Stmt) {
        match stmt {
            thir::Stmt::Local { .. } => todo!(),
            thir::Stmt::Expr(expr) => {
                // the value that generated by lowering expr is assign to local of return value
                let place = self.body.local_return();

                let rvalue = {
                    let operand = self.lower_expr(expr);
                    RValue::Use(operand)
                };

                let stmt = Statement::Assign(Box::new((place, rvalue)));
                self.body.blocks[self.block_at].stmts.push(stmt);
            }
            thir::Stmt::Semi(_) => todo!(),
        }
    }

    fn lower_expr(&mut self, expr: &thir::Expr) -> Operand {
        match expr {
            thir::Expr::Binary { .. } => todo!(),
            thir::Expr::Unary { .. } => todo!(),
            thir::Expr::Lit { lit, ty } => self.lower_expr_lit(lit, *ty),
            thir::Expr::Ident { .. } => todo!(),
        }
    }

    fn lower_expr_lit(&mut self, lit: &thir::Lit, _ty: ty::Ty) -> Operand {
        match &lit {
            thir::Lit::Int(thir::LitInt { value }) => {
                let scalar = Constant::Scalar(ScalarInt {
                    data: *value,
                    size: 32,
                });
                Operand::Constant(Box::new(scalar))
            }
        }
    }
}
